services:
  react:
    image: node:20-alpine
    container_name: react
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm start"